name: The Sparkling
favicon: null
layout_spectrum: 0.65819
typography_spectrum: 0.47269
title: Portraits - Moments - Emotions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141414'
    - '#0c0c0c'
    - '#242426'
    - '#020202'
    - '#313132'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
