name: The Sparkling
favicon: null
layout_spectrum: 0
typography_spectrum: 0.47269
title: Portraits - Moments - Emotions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#242424'
    - '#c9c9c9'
    - '#fe000c'
    - '#fe567d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
