name: The Sparkling
favicon: null
layout_spectrum: 0.06661
typography_spectrum: 0.47269
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#373739'
    - '#151515'
    - '#bebfc3'
    - '#898a8e'
    - '#68696d'
  brandStrength: 0.75
  lightness: 0.6365722331684083
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
